# Full configuration reference available at:
# https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/reference.html
dh_auditor:
    enabled: true
    providers:
        doctrine:
            table_prefix: 'misA'
            table_suffix: '_audit'
            ignored_columns:
                - createdAt
                - updatedAt
                - password
                - lastLogin
            entities:
                App\Entity\User: ~
                App\Entity\UserGroup: ~
                

       
