security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
        ldap_user_provider:
            id: App\Security\LdapUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        mobile:
            pattern: ^/mobile/*
            anonymous: lazy
            provider: ldap_user_provider
            form_login:
                    remember_me: true
                    login_path: mobile_login
                    check_path: mobile_login
            guard:
                authenticators:
                    - App\Security\MobileLoginFormAuthenticator
                entry_point: App\Security\MobileLoginFormAuthenticator
            logout:
                path: mobile_logout
                target: mobile_login

        main:
            anonymous: true
            lazy: true
            provider: ldap_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_login

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
       - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/mobile, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/feed/back/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/achievement/goalHome, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/achievement/kpivis, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/achievement/planHome, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/changeLocale, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/student_report, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/employee_report, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/*, roles: ROLE_USER }
    